name = "spanishlu-grambook"
main = "src/index.js"
compatibility_date = "2024-07-06"
compatibility_flags = ["nodejs_compat"]

# 添加你的 Cloudflare 帳戶信息
account_id = "96192595524d0d5e2d0143c3869dacc0"  # 替換為你的 Account ID
workers_dev = true


# 環境配置
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
